# mkinitcpio.conf for ArchNesic v3
# Minimal initramfs with Plymouth boot splash

MODULES=()
BINARIES=()

FILES=()

HOOKS=(
  base
  udev
  sd-plymouth
  autodetect
  modconf
  block
  filesystems
  keyboard
  fsck
)

COMPRESSION="zstd"
COMPRESSION_OPTIONS=(-19)

# No microcode early (handled by bootloader)
