# mkinitcpio.conf for ArchNesic
# Minimal initramfs — just enough to find the squashfs

MODULES=()
BINARIES=()

FILES=()

HOOKS=(
  base
  udev
  autodetect
  modconf
  block
  filesystems
  keyboard
  fsck
)

COMPRESSION="zstd"
COMPRESSION_OPTIONS=(-19)

# No microcode early (handled by bootloader)
