title   Amnesic Wipe (Secure Boot)
linux   /%INSTALL_DIR%/boot/vmlinuz-linux
initrd  /%INSTALL_DIR%/boot/intel-ucode.img
initrd  /%INSTALL_DIR%/boot/amd-ucode.img
initrd  /%INSTALL_DIR%/boot/initramfs-%ARCH%.img
options archisobasedir=%INSTALL_DIR% archisolabel=%ISO_LABEL% \
        toram quiet splash loglevel=3 \
        slab_nomerge init_on_alloc=1 init_on_free=1 \
        lockdown=confidentiality \
        spectre_v2=on spec_store_bypass_disable=on \
        module.sig_enforce=1
