#
# /etc/pacman.conf for amnesic-wipe live ISO
#

[options]
HoldPkg       = pacman glibc
Architecture  = auto
SigLevel      = Required DatabaseOptional
LocalFileSigLevel = Optional

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist
